name: Mike Fowler
author: Mike Fowler
url: 'http://mikefowler.me'
email: mike@mikefowler.me

css: '/assets/css'
js: '/assets/js'
images: '/assets/images'

markdown: redcarpet

pygments: true
permalink: /:year/:month/:day/:title/

exclude: [
  'node_modules',
  'assets/sass',
  'Gruntfile.js',
  'mikefowler.me.sublime-project',
  'mikefowler.me.sublime-workspace',
  'package.json',
  'README.md',
  'vendor',
  'config.rb',
  'Gemfile',
  'Gemfile.lock',
  'CNAME'
]